// <autogenerated>
//   This file was generated by T4 code generator ExecuteTemplate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


namespace Example.ConsoleApp.T4
{
	public class Test
	{
	public Test(){}


	}
}
